steps:
  # 1. Build the Docker image
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}
      - .

  # 2. Push the image to Artifact Registry
  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}
    waitFor:
      - build

  # 3. Download Cloud SQL Auth Proxy
  - id: download-proxy
    name: gcr.io/cloud-builders/curl
    args:
      - -o
      - /workspace/cloud-sql-proxy
      - -L
      - https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.3/cloud-sql-proxy.linux.amd64
    waitFor:
      - "-"

  - id: chmod-proxy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: chmod
    args:
      - +x
      - /workspace/cloud-sql-proxy
    waitFor:
      - download-proxy

  # 4. Run database migrations with Cloud SQL Auth Proxy
  - id: migrate
    name: gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}
    entrypoint: sh
    args:
      - -c
      - |
        /workspace/cloud-sql-proxy ${_CLOUD_SQL_INSTANCE} --port 5432 &
        PROXY_PID=$$!
        for i in 1 2 3 4 5; do sleep 1; echo "Waiting for proxy..."; done
        DB_NAME=$$(echo "$$DATABASE_URL" | cut -d'?' -f1 | rev | cut -d'/' -f1 | rev)
        DB_AUTH=$$(echo "$$DATABASE_URL" | cut -d'@' -f1)
        export DATABASE_URL="$${DB_AUTH}@127.0.0.1:5432/$${DB_NAME}"
        echo "DATABASE_URL host overridden to 127.0.0.1:5432"
        uv run alembic upgrade head
        EXIT_CODE=$$?
        kill $$PROXY_PID || true
        exit $$EXIT_CODE
    secretEnv:
      - DATABASE_URL
    waitFor:
      - push
      - chmod-proxy

  # 5. Deploy Cloud Run services (parallel)
  - id: deploy-public
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME_PUBLIC}
      - --image=gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}
      - --region=us-central1
      - --project=hotelly--ia
    waitFor:
      - migrate

  - id: deploy-worker
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME_WORKER}
      - --image=gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}
      - --region=us-central1
      - --project=hotelly--ia
    waitFor:
      - migrate

availableSecrets:
  secretManager:
    - versionName: projects/hotelly--ia/secrets/${_DB_SECRET_NAME}/versions/latest
      env: DATABASE_URL

substitutions:
  _IMAGE_TAG: "staging"
  _SERVICE_NAME_PUBLIC: "hotelly-public-staging"
  _SERVICE_NAME_WORKER: "hotelly-worker-staging"
  _CLOUD_SQL_INSTANCE: ""
  _DB_SECRET_NAME: "hotelly-staging-database-url"

images:
  - gcr.io/hotelly--ia/hotelly-v2:${_IMAGE_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
